### ISSUE TITLE
Rapid item creation

### ISSUE THREAD

**Issue by bradgessler** [thingybase/community#1]
The current Thingybase input requires too many taps/clicks when walking around and/or rapidly adding items to a container. Make it possible to quickly add a bunch of items, like a TODO list, and fill in the details later.

This is useful when adding a bunch of items into a box, shelf, or whatever.

After the item is created, it would be helpful if there was a some way to tap on a link/button to view and/or edit the details, but make it easy to ignore for the rapid fire addition of more items.

**Comment by bradgessler** [comment]
Started cranking on a more rapid way of entering items. Here's where it's at so far:

https://user-images.githubusercontent.com/4628/126934274-31994900-a0d6-4c06-aa7b-b5ad0ba3eb0a.MP4

There's still some heavy tweaking and the UI could be streamlined a bit, but I'm settling on the idea of this roughly being the primary way of creating items. Some things I'm still sorting out:

1. The drop-down should "stick". If you select `Container`, it should stay that way until you change it.
2. The drop-down should be smaller or not appear on mobile. I might change this to a different UI affordance.
3. I need to figure out how to make it more obvious that the order changes, and is sorted by "created at", with the most recent up top. I do this so there's immediate visual feedback that an item is created.

**Comment by ab623** [comment]
@bradgessler - This looks excellent, and exactly what I originally had in mind!

On feedback for your points, I'll take them one by one.
1. I agree with this
2. I think this makes sense too. On mobile rapid item creation is key. Having to go through a longer flow for container creation on mobile is fine with me. 
3. I believe the usual sort order for items is alphabetical, but these are being added in a created order. I would prefer to keep it in alphabetical, potentially some sort of 1 second toast to show it was created successfully?

**Comment by bradgessler** [comment]
Rad. I'll change up creation to look like this across the board. I think I can have the `[ Item | Container]` drop-down on mobile. We'll see how that works and can easily change it later if its not doing it.

As for the sort order, I agree it would be great to preserve that when switching between viewing and creation. I'm going to have to work on how the confirmation message is displayed. It will be toast-ish, but not quite a toast because layers don't work that well for UI's that target multiple viewport sizes. I've got a few ideas I'm going to try out and will either deploy it or show another video here.

**Comment by bradgessler** [comment]
Here’s a mock-up of where I might take this. Need to mull on the mobile form factor a bit more. 

![IMG_0800](https://user-images.githubusercontent.com/4628/127606434-e14de3fa-945f-4f31-9ad1-e189a13f751e.png)

And here’s what that might change the look of other screens:

![IMG_0801](https://user-images.githubusercontent.com/4628/127606593-0ed6cb9d-b653-4ec9-94ce-149f339795fd.png)

**Comment by bradgessler** [comment]
Deployed rapid item creation for all non-root items. Here's what it looks like on mobile:

https://user-images.githubusercontent.com/4628/127683443-fd928c85-6dc4-4d61-9f13-bf2f216f5530.MOV

A small confirmation message is displayed after creation so it's easier to view or edit and item.

It's pretty basic right now, but it works.

Next up: I'm going to think about creating items from the root. I'm leaning more towards making it difficult to rapidly create items there and instead encourage people to make rooms, etc.

**Comment by bradgessler** [comment]
I just rolled with this for root items & containers. Closing this out since its complete., but please feel free to reply with feedback on where this landed and I'll make tweaks or create another issue.
