### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by forcetrainer** [thingybase/community#20]
I recently attempted to search for an item via the search bar, but it returned no results. All items are still in the inventory, but search appears to no longer be functioning.

**Comment by bradgessler** [comment]
Fixed! Thanks for reporting this.

### Technical note

Cause: upgrade from Turbo 7 to Turbo 8 ignored the `turbo-data-method: get` for the search form and was triggering a `POST` request instead of a `GET`.
