### ISSUE TITLE
Include container hierarchy as part of item export

### ISSUE THREAD

**Issue by forcetrainer** [thingybase/community#21]
The current CSV export includes all items with a link to the Thingybase URL, but it does not include a field to indicate container in which items may be located. Since items can be nested seemingly infinitely (I'm sure it breaks at some point), a field called "Contained In" would help identify where items are located when export.  

Here is an example:

| Name | Container | URL | Created at | Updated at | Expires at |
| --- | --- | --- | --- | --- | --- | 
| Bin 1 | Basement | www.thinybase.com | 2024-01-01 | 2024-01-01 | 2025-01-01 |
| Washers | Bin 1 | www.thingbase.com | 2024-01-01 | 2024-01-01 | 2025-01-01 |

**Comment by bradgessler** [comment]
Great idea! Here's what the new CSV export looks like:

```csv
Name,URL,Container,Created at,Updated at,Expires at
Kitchen,http://localhost:5070/items/ByOyCy0rB7hheQFCANUETq,Home,2024-02-02 05:25:58 UTC,2024-02-02 05:25:58 UTC,""
Refrigerator,http://localhost:5070/items/DLeI5GBIFlzZClANVaxMFr,Kitchen,2024-02-02 05:25:58 UTC,2024-02-02 05:25:58 UTC,""
Gooster,http://localhost:5070/items/GqZJbZ5w4poEdrNnskqnAC,Home,2024-02-06 02:58:33 UTC,2024-02-06 02:58:33 UTC,""
Top shelf,http://localhost:5070/items/C9AH8lPQ4XLiQVgnBJ1AyY,Shelf,2024-02-02 05:25:58 UTC,2024-02-02 05:25:58 UTC,""
```
