### ISSUE TITLE
Make more of a distinction between containers & items

### ISSUE THREAD

**Issue by bradgessler** [thingybase/community#4]
As you can see, there's no great way to tell the difference between a container and an item:

<img width="1349" alt="Screen Shot 2021-07-20 at 00 09 46" src="https://user-images.githubusercontent.com/4628/126260559-78d481f1-f14e-447e-ac8e-3d7ed4a5750f.png">

Some ideas:

1. Display the number of items in a container in the text description below the name of the container. e.g. "1 item", "12 items", etc.
2. Add the text "Item" or "Container" to the description below the name of the container.
3. Separate items & containers. This could vary from simply having all of the containers up top and items at the bottom, or it could be more prominent with a header "Items" and "Containers" and the respective entities below them.

Questions:

1. If I display the number of items in a container, should it be for all items/containers within that portion of the tree? Or should it count the number of children within that node?

**Comment by ab623** [comment]
I was thinking it could look something like this:

![image](https://user-images.githubusercontent.com/3438974/126513742-1857def4-28d6-4972-8189-5ddff8f391c1.png)

Also having the containers grouped at the top, and items underneath. Similar to a folder/file hierarchy in any file browser. In this case think having the Item/Container label underneath might be redundant, but I still think it is nice to keep there.

Lastly I think showing the items in the immediate child container. I don't think a recursive item number would be very useful.

**Comment by bradgessler** [comment]
I did a really basic thing and make a distinction between "Item" and "Container" with a simple label:

<img width="417" alt="Screen Shot 2021-07-30 at 15 30 30" src="https://user-images.githubusercontent.com/4628/127702838-c800d84e-f442-4c22-b417-209ff257039b.png">

I have a prototype of displaying the contents of the container, but it needs to be refactored to deal with some performance issues.

**Comment by bradgessler** [comment]
This has been deployed:

<img width="1537" alt="Screen Shot 2021-08-05 at 21 29 24" src="https://user-images.githubusercontent.com/4628/128442170-f1d58d0d-1769-4d58-9c0f-c02dbe5564e2.png">

I'm pretty sure if I introduce types beyond "items" and "containers" that I'll have to change it to just "Container has *n* things", so don't fall in love with this too much. We'll see what the future brings.

If the counts are off, please comment here or create a new issue and I can run a query that will correct all the accounts and try to troubleshoot why the counts deviated.
